spawn:
  world: "world"
  pos1:
    x: 20.0
    y: 50.0
    z: -10.0
  pos2:
    x: -10.0
    y: 90.0
    z: 20.0

commands:
  mytps:
    names:
      - "mytps"
      - "anothertps"
    msg: "ТэПэЭс: %.1f"

menus:
  tps:
    format: "TPS: %.1f"